import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "InvestMate",
  description: "Navigate Your Financial Future with Confidence.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "drizzle-orm",
    "drizzle",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "finance-app",
    "transactions",
    "dashboard",
    "accounts",
    "clerk",
    "neon-db",
    "sonner",
    "zustand",
    "zod",
    "sql",
    "postgresql",
    "honojs",
    "honojs-api",
    "hono-api",
    "lucide-react",
    "recharts",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Sharli Khot",
    url: "https://github.com/KhotSharli",
  },
} as const;

export const links = {
  sourceCode: "https://github.com/KhotSharli/InvestMate",
} as const;